# Generated by Django 4.1.5 on 2023-01-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('concentration', models.DecimalField(decimal_places=10, max_digits=10)),
                ('concentration_units', models.CharField(max_length=10)),
                ('rxcui_code', models.IntegerField()),
                ('route', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
