# Generated by Django 4.1.5 on 2023-01-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='concentration',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10),
        ),
    ]
