# Generated by Django 4.1.5 on 2023-01-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0002_alter_drug_concentration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='concentration',
            field=models.FloatField(blank=True),
        ),
    ]
