# Generated by Django 4.1.5 on 2023-01-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0003_alter_drug_concentration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
