# Generated by Django 4.1.5 on 2023-01-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0004_alter_drug_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='er_dose',
            field=models.FloatField(default=0),
        ),
    ]
