# Generated by Django 4.1.5 on 2023-02-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0008_alter_fluid_fluid_rate_increment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluid',
            name='administration_note',
            field=models.CharField(default='', max_length=50),
        ),
    ]
