# Generated by Django 4.1.5 on 2023-02-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0010_alter_fluid_administration_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='route',
            field=models.CharField(max_length=50),
        ),
    ]
