# Generated by Django 4.1.4 on 2023-04-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0011_alter_drug_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
