# Generated by Django 4.1.4 on 2023-04-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0012_alter_drug_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='cat_high_dose',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drug',
            name='cat_low_dose',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drug',
            name='dog_high_dose',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='drug',
            name='dog_low_dose',
            field=models.FloatField(default=0),
        ),
    ]
